### ISSUE TITLE
deprecated?

### ISSUE THREAD

**Issue by leebenson** [SlexAxton/yepnope.js#228]
From the Modernizr 3 tracker:

>Modernizr.load has been deprecated in favour of using yepnope.js directly; from v3.0, yepnope.js must be included in the page in order for Modernizr.load to work: calling .load() will simply pass `

Does this mean that YepNode.js is not longer deprecated?

**Comment by kumarharsh** [comment]
No idea what's going on with these two projects... modernizr already has very poor docs wrt this, and here it's an even confusing doc which says it has deprecated itself, but still houses the library

**Comment by SlexAxton** [comment]
Yepnope as it was included in Modernizr (`Modernizr.load` was just an alias to `yepnope`) is deprecated, and has been removed from Modernizr. You're welcome to grab the previous version and use it. A deprecation warning generally means that the old libraries still work, but that it's no longer going to be worked on.

The master branch has a version of yepnope that's more in line with what you *should* be doing, but also isn't a maintained, suggested library. Modernizr points you at the yepnope library in case you need backwards compatibility, not as a suggested solution. Use a build tool.

If the docs are poor, please, by all means feel free to contribute back more clear updates.

**Comment by SlexAxton** [comment]
> here it's an even confusing doc which says it has deprecated itself, but still houses the library

I'm not sure what you want. Should I delete the repo?

**Comment by kumarharsh** [comment]
No, I don't want you to delete the repo. I was just stumped by the wording of the notice:

> We have replaced this repo with a script...

I assumed this repo was discontinued, and replaced with a simple gist or something. That confused me, because the repo, and the code was all there. Then when I looked into the commit history, it became clear that the "repo" you refer here is the old library, not the whole repo as such.

**Comment by kumarharsh** [comment]
No, I don't want you to delete the repo. I was just stumped by the wording of the notice:

> We have replaced this repo with a script...

I assumed this repo was discontinued, and replaced with a simple gist or something. That confused me, because the repo, and the code was all there. Then when I looked into the commit history, it became clear that the "repo" you refer here is the old library, not the whole repo as such.
