### ISSUE TITLE
Confirm the license version

### ISSUE THREAD

**Issue by PeterDaveHello** [SlexAxton/yepnope.js#230]
Hi there,

May I know the version of MIT you are using? I think it's as important as a license, many thanks!

ref: https://spdx.org/licenses/

**Comment by SlexAxton** [comment]
As far as I can tell, there's only one version of the MIT license:

https://spdx.org/licenses/MIT.html

**Comment by PeterDaveHello** [comment]
Okay, because [new-bsd-license](https://github.com/SlexAxton/yepnope.js#new-bsd-license) usually means BSD-2/3-Clause I think.

**Comment by SlexAxton** [comment]
We have the license in the code, which I think should remove ambiguity?

https://github.com/SlexAxton/yepnope.js/blob/master/LICENSE.md

**Comment by PeterDaveHello** [comment]
hmmm ... what about make "new-bsd-license" just "MIT" in readme?

**Comment by SlexAxton** [comment]
Sorry, all of those licenses are the 'new bsd' license, not MIT. I thought you were saying that I still had an  MIT license somewhere and that it was mismatching against the new bsd license.

I think there's no ambiguity there, since it's inlined in the readme and in the LICENSE.md file, but I mean this license:

https://spdx.org/licenses/BSD-3-Clause.html

**Comment by PeterDaveHello** [comment]
Okay, sorry for the misunderstanding, would you consider to say "BSD-3-Clause" in readme?

**Comment by SlexAxton** [comment]
It's right above a 3 clause license, but I'll happily merge a PR that makes that clarification.

**Comment by PeterDaveHello** [comment]
Is this okay?

**Comment by SlexAxton** [comment]
Might as well update the package.json too

**Comment by PeterDaveHello** [comment]
Okay

**Comment by PeterDaveHello** [comment]
Updated. in #232
